name: GitHub Actions Demo
on: [push]

jobs:
  my-job-02:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "execute my-job-01"

      - name: Check for changes
        run: |
          diff_output=$(diff petstore.yaml petstore2.yaml)
          if [ $? -eq 0 ]; then
              # 差分が無かった場合
              echo "No changes."
              echo "is_editted=0" >> $GITHUB_OUTPUT
          else
              # 差分があった場合
              echo "Changes found."
              echo "is_editted=0" >> $GITHUB_OUTPUT
          fi
